// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ureR0uLIiSj08FCO2DIxXK5kuzAZY3w',
    appId: '1:862480584800:web:fc39f5fd46b4ee47fd7305',
    messagingSenderId: '862480584800',
    projectId: 'csa-7e5c6',
    authDomain: 'csa-7e5c6.firebaseapp.com',
    storageBucket: 'csa-7e5c6.firebasestorage.app',
    measurementId: 'G-JMPBBCEM0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARVdRRIfXMgngdltTwfBce3-BC3L_Sm-A',
    appId: '1:862480584800:android:2ec33485658184ebfd7305',
    messagingSenderId: '862480584800',
    projectId: 'csa-7e5c6',
    storageBucket: 'csa-7e5c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlLcHkFshouu64nC8f0GnvPVrjBreWPBQ',
    appId: '1:862480584800:ios:9ce7363ebf06cd3dfd7305',
    messagingSenderId: '862480584800',
    projectId: 'csa-7e5c6',
    storageBucket: 'csa-7e5c6.firebasestorage.app',
    iosBundleId: 'com.example.astroot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlLcHkFshouu64nC8f0GnvPVrjBreWPBQ',
    appId: '1:862480584800:ios:9ce7363ebf06cd3dfd7305',
    messagingSenderId: '862480584800',
    projectId: 'csa-7e5c6',
    storageBucket: 'csa-7e5c6.firebasestorage.app',
    iosBundleId: 'com.example.astroot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0ureR0uLIiSj08FCO2DIxXK5kuzAZY3w',
    appId: '1:862480584800:web:12c97b8a5df27ca6fd7305',
    messagingSenderId: '862480584800',
    projectId: 'csa-7e5c6',
    authDomain: 'csa-7e5c6.firebaseapp.com',
    storageBucket: 'csa-7e5c6.firebasestorage.app',
    measurementId: 'G-40ZMMV24SZ',
  );
}
